name: Run Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
          import requests
          url = "https://sslbl.abuse.ch/blacklist/sslipblacklist.txt"
          f = (requests.get(url)).text
          a = open("blacklist.rsc", "w")

          for line in f.splitlines():
            if not line.startswith('#'):
              a.write(("/ip firewall address-list add address=") +
                line + (" comment=blacklist list=blacklist\n"))
